import { Sparkles, BarChart3, List, MessageSquare, Link, BookOpen, Settings, Bot, PartyPopper, Stethoscope, Scale, Building2, GraduationCap, QrCode } from 'lucide-react';

const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    title: 'ברוכה הבאה למערכת! 🌸',
    content: 'המערכת מנהלת את כל התקשורת עם הלקוחות שלך — מהפנייה הראשונה ועד לתור.\nהבוט בוואטסאפ עובד אוטומטית, ואת צריכה רק לפקח ולעדכן.',
    icon: Sparkles,
    iconColor: 'text-primary',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
    canPractice: false,
  },
  {
    id: 'dashboard',
    title: 'לבדוק סטטוס לקוח',
    content: 'בדאשבורד את רואה כמה פניות יש בכל סטטוס.\nלחצי על אחת מההתראות (לידים חדשים / הודעות לבדיקה) כדי לעבור ישירות לפניות הרלוונטיות.',
    tip: 'הכרטיסים הכתומים והאדומים דורשים תשומת לב — לחצי עליהם!',
    icon: BarChart3,
    iconColor: 'text-emerald-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="alert-cards"]',
    navigateTo: '/Dashboard',
    canPractice: true,
    practiceLabel: 'לחצי על התראה 🎯',
  },
  {
    id: 'requests',
    title: 'להבין סטטוסים ופניות',
    content: 'כל פנייה עוברת דרך שלבים:\nליד חדש → שולם → שאלון → נקבע תור → הושלם.\n\nהבוט מטפל אוטומטית ברוב המעברים. את יכולה לשנות סטטוס ידנית או ללחוץ על פנייה לפרטים.',
    tip: 'לחצי על שם הלקוח כדי לראות את כל הפרטים והיסטוריית הטיפול.',
    icon: List,
    iconColor: 'text-blue-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="requests-table"]',
    navigateTo: '/ServiceRequests',
    canPractice: true,
    practiceLabel: 'פתחי פנייה 🎯',
  },
  {
    id: 'bot-content',
    title: 'לעדכן הודעות הבוט',
    content: 'כאן יושבים כל הטקסטים שהבוט שולח ללקוחות.\nאת יכולה לערוך את הנוסח של כל הודעה.',
    tip: '⚠️ חשוב: לא לשנות את ה-key ולא למחוק placeholder כמו {שם} או {קישור} — הם מוחלפים אוטומטית.',
    icon: MessageSquare,
    iconColor: 'text-violet-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="bot-content-table"]',
    navigateTo: '/BotContent',
    canPractice: true,
    practiceLabel: 'ערכי הודעה 🎯',
  },
  {
    id: 'service-content',
    title: 'לעדכן קישורים וקבצים',
    content: 'כאן יושבים כל הקישורים — תשלום, שאלון, הסכם, יומן.\nכשמשהו משתנה (למשל קישור תשלום חדש), את מעדכנת כאן ולא בהודעות.',
    tip: 'הפרדה ברורה: BotContent = טקסטים, ServiceContent = קישורים.',
    icon: Link,
    iconColor: 'text-orange-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="service-content-table"]',
    navigateTo: '/ServiceContent',
    canPractice: true,
    practiceLabel: 'ערכי קישור 🎯',
  },
  {
    id: 'lectures',
    title: 'קטלוג הרצאות',
    content: 'כאן מנהלים את ההרצאות — שם, סרטון, PDF, מחיר.\nהבוט שולף מכאן אוטומטית את החומרים ללקוח.',
    tip: 'אפשר להוסיף הרצאה בודדת, סדרה, או סדנה.',
    icon: BookOpen,
    iconColor: 'text-purple-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="lectures-table"]',
    navigateTo: '/Lectures',
    canPractice: true,
    practiceLabel: 'הוסיפי הרצאה 🎯',
  },
  {
    id: 'route-consultation',
    title: 'מסלול ייעוץ גנטי',
    content: '🔀 שני נתיבים:\n1. אוטיזם ותסמונות גנטיות\n2. מחלות כרוניות (~8 אפשרויות: פוריות, הריון, גיל המעבר, סוכרת, דיכאון, מחלות מעי, סרטן, אוטיזם)\n\nכל האפשרויות עוברות באותו מסלול.\n\n📋 דוגמה — "סוכרת":\nסרטון כללי → "צפיתי" → בחירת סוגיה → סרטון+PDF סוכרת → "צפיתי וקראתי" → חומר נוסף → סודיות → שאלון → תשלום → תורים',
    tip: '📦 לערוך: תוכן הבוט (סנני "ייעוץ") + ניהול תוכן (סנני "ייעוץ")',
    icon: Stethoscope,
    iconColor: 'text-blue-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="bot-content-table"]',
    navigateTo: '/BotContent',
    canPractice: true,
    practiceLabel: 'תרגלי — סנני "ייעוץ" 🎯',
  },
  {
    id: 'route-legal',
    title: 'מסלול חוות דעת משפטית',
    content: '⚠️ אין שאלון ואין מחירון!\n\n📋 המסלול:\nהסבר על השירות → "מעוניינת" → חומר נוסף → הסכם (PDF) → "קראתי" → תשלום (Paybox + ברקוד Bit) → "שילמתי" → סודיות + בקשת מסמכים למייל → "שלחתי" → תיאום פגישה → "קבעתי" → הנחיות הגעה',
    tip: '📦 לערוך: תוכן הבוט (סנני "משפטי") + ניהול תוכן (סנני "משפטי")',
    icon: Scale,
    iconColor: 'text-violet-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="service-content-table"]',
    navigateTo: '/ServiceContent',
    canPractice: true,
    practiceLabel: 'תרגלי — סנני "משפטי" 🎯',
  },
  {
    id: 'route-clinic',
    title: 'מסלול קליניקה (השכרת חדרים)',
    content: '🔀 שני נתיבים:\n\n--- שוכר ותיק ---\nמחירון → "קראתי" → תיאום הגעה → "קבעתי" → הנחיות הגעה\n\n--- מתעניין חדש ---\nבחירת סוג חדר (שיחה/טיפול/רופא) → תמונה+סרטון → "צפיתי" → מידע+מחירון → "קראתי" → תיאום → "קבעתי" → הנחיות הגעה',
    tip: '📦 לערוך: תוכן הבוט (סנני "קליניקה") + ניהול תוכן (סנני "קליניקה")',
    icon: Building2,
    iconColor: 'text-teal-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="bot-content-table"]',
    navigateTo: '/BotContent',
    canPractice: true,
    practiceLabel: 'תרגלי — סנני "קליניקה" 🎯',
  },
  {
    id: 'route-lectures',
    title: 'מסלול הרצאות',
    content: '🔀 שלושה סוגים:\n\n1. סדרת הרצאות — קישור לדף הסדרה → "קראתי" → תיאום\n2. הרצאה בודדת — רשימת הרצאות → בחירת מספר → סרטון+PDF → "קראתי" → תיאום\n3. סדנת ביופידבק — סרטון+PDF → "צפיתי וקראתי" → תיאום\n\n📋 דוגמה — "האנטומיה של אושר":\nבוחרים מספר מהרשימה → מקבלים סרטון + PDF → "קראתי" → קישור תיאום → "קבעתי" → הנחיות הגעה',
    tip: '📦 לערוך: תוכן הבוט (סנני "הרצאות") + קטלוג הרצאות (PDF+סרטון של כל הרצאה)',
    icon: GraduationCap,
    iconColor: 'text-amber-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="lectures-table"]',
    navigateTo: '/Lectures',
    canPractice: true,
    practiceLabel: 'תרגלי — ראי הרצאות 🎯',
  },
  {
    id: 'route-post-lecture',
    title: 'מסלול פוסט הרצאה (QR)',
    content: '⚡ מופעל כשמשתתף סורק QR בסוף הרצאה\n\n📋 המסלול:\nאיסוף פרטים (שם+טלפון+מייל) → PDF סיכום ההרצאה → "קראתי" → הצעת ספר → "הזמנתי"/"המשך" → הצעת הרצאות נוספות → כן=מעבר למסלול הרצאות / לא=סיום',
    tip: '📦 לערוך: תוכן הבוט (סנני "פוסט הרצאה") + ניהול תוכן (סנני "פוסט הרצאה")\n💡 ה-QR נמצא בניהול תוכן → כרטיס QR',
    icon: QrCode,
    iconColor: 'text-rose-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="service-content-table"]',
    navigateTo: '/ServiceContent',
    canPractice: true,
    practiceLabel: 'תרגלי — סנני "פוסט הרצאה" 🎯',
  },
  {
    id: 'settings',
    title: 'הגדרות מערכת',
    content: 'כאן מפעילים/מכבים את הבוט, מגדירים טלפונים לבדיקה, ומנהלים הגדרות כלליות.',
    tip: 'כשרוצים לבדוק את הבוט בלי לשלוח ללקוחות אמיתיים — מכבים את הבוט ומוסיפים טלפון לבדיקה.',
    icon: Settings,
    iconColor: 'text-gray-600',
    position: 'bottom',
    highlightSelector: '[data-tutorial="system-settings"]',
    navigateTo: '/SystemSettings',
    canPractice: true,
    practiceLabel: 'בדקי הפעלת בוט 🎯',
  },
  {
    id: 'agent',
    title: 'ההנחיות של הבוט',
    content: 'הנחיות הבוט נמצאות ב-Base44 ← Agents ← dr_adri_bot.\nשם תוכלי לראות את כל ההגיון שלו — מתי הוא שולח מה ובאיזה סדר.',
    tip: '⚠️ לא לשנות בלי תיאום עם המפתחת.',
    icon: Bot,
    iconColor: 'text-cyan-600',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
    canPractice: false,
  },
  {
    id: 'finish',
    title: 'את מוכנה! 🌷',
    content: 'לכל שאלה או בעיה — פני לעינת.\nכפתור ❓ בתפריט תמיד יחזיר את המדריך הזה.',
    icon: PartyPopper,
    iconColor: 'text-pink-500',
    position: 'center',
    highlightSelector: null,
    navigateTo: null,
    canPractice: false,
  },
];

export default TUTORIAL_STEPS;